"""Deterministic generators for contracts derived from executable code."""

from __future__ import annotations

import asyncio
import json
import re
from typing import Any

PUBLIC_SCHEMA_BASE = "https://semantic-rails.com/schemas/"


def _operation_id(method: str, path: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", path.lower()).strip("_")
    return f"{method.lower()}_{slug}"


def http_openapi_document() -> dict[str, Any]:
    """Build the public HTTP v1 OpenAPI document from the routing table."""

    from semantic_rails import __version__
    from semantic_rails.http_core import API_VERSION, PUBLIC_V1_ROUTES

    paths: dict[str, dict[str, Any]] = {}
    for route in PUBLIC_V1_ROUTES:
        method = str(route["method"]).lower()
        path = str(route["path"])
        operation: dict[str, Any] = {
            "operationId": _operation_id(method, path),
            "summary": f"Semantic Rails {path.rsplit('/', 1)[-1]}",
            "responses": {
                "200": {
                    "description": "Semantic Rails v1 response envelope",
                    "content": {
                        "application/json": {
                            "schema": {"$ref": "#/components/schemas/ResponseEnvelope"}
                        }
                    },
                },
                "400": {
                    "description": "Invalid request",
                    "content": {
                        "application/json": {
                            "schema": {"$ref": "#/components/schemas/ResponseEnvelope"}
                        }
                    },
                },
                "401": {
                    "description": "Authentication failed",
                    "content": {
                        "application/json": {
                            "schema": {"$ref": "#/components/schemas/ResponseEnvelope"}
                        }
                    },
                },
            },
            "security": [{"bearerAuth": []}, {"apiKeyAuth": []}],
        }
        if method == "post":
            operation["requestBody"] = {
                "required": False,
                "content": {
                    "application/json": {
                        "schema": (
                            {
                                "oneOf": [
                                    {"$ref": "./query_ir.v1.json"},
                                    {
                                        "type": "object",
                                        "properties": {
                                            "query": {"$ref": "./query_ir.v1.json"},
                                            "request_id": {"type": "string"},
                                            "policy_context": {"type": "object"},
                                        },
                                        "additionalProperties": True,
                                    },
                                ]
                            }
                            if path in {"/api/v1/validate", "/api/v1/compile", "/api/v1/query"}
                            else {"type": "object", "additionalProperties": True}
                        )
                    }
                },
            }
        paths.setdefault(path, {})[method] = operation
    return {
        "openapi": "3.1.0",
        "info": {
            "title": "Semantic Rails Query API",
            "version": API_VERSION,
            "description": (
                f"Public Semantic Rails HTTP {API_VERSION} contract. "
                f"Generated by semantic-rails {__version__}."
            ),
        },
        "servers": [{"url": "/"}],
        "paths": paths,
        "components": {
            "securitySchemes": {
                "bearerAuth": {"type": "http", "scheme": "bearer"},
                "apiKeyAuth": {"type": "apiKey", "in": "header", "name": "X-Semantic-API-Key"},
            },
            "schemas": {
                "Issue": {
                    "type": "object",
                    "required": ["code", "message"],
                    "properties": {
                        "code": {"type": "string"},
                        "message": {"type": "string"},
                        "severity": {"type": "string"},
                        "stage": {"type": "string"},
                        "details": {"type": "object", "additionalProperties": True},
                        "recovery_hints": {"type": "array", "items": {"type": "object"}},
                    },
                    "additionalProperties": True,
                },
                "ResponseEnvelope": {
                    "type": "object",
                    "required": [
                        "ok",
                        "status",
                        "api_version",
                        "request_id",
                        "package_id",
                        "warnings",
                        "errors",
                    ],
                    "properties": {
                        "ok": {"type": "boolean"},
                        "status": {"type": "string"},
                        "api_version": {"const": API_VERSION},
                        "request_id": {"type": "string"},
                        "package_id": {"type": "string"},
                        "warnings": {
                            "type": "array",
                            "items": {"$ref": "#/components/schemas/Issue"},
                        },
                        "errors": {
                            "type": "array",
                            "items": {"$ref": "#/components/schemas/Issue"},
                        },
                        "error": {"$ref": "#/components/schemas/Issue"},
                        "recovery_hints": {"type": "array", "items": {"type": "object"}},
                        "request_context": {"type": "object"},
                        "timing_ms": {"type": "number", "minimum": 0},
                    },
                    "additionalProperties": True,
                },
            },
        },
    }


def query_mcp_manifest_document() -> dict[str, Any]:
    """Build the complete query-MCP v1 manifest from declarative definitions."""

    from semantic_rails import __version__
    from semantic_rails.mcp import (
        MCP_INTERFACE_VERSION,
        MCP_RESULT_SCHEMA,
        list_prompt_definitions,
        list_resource_definitions,
        list_tool_definitions,
    )
    from semantic_rails.mcp_server import (
        MCP_PROTOCOL_VERSION,
        MCP_SUPPORTED_PROTOCOL_VERSIONS,
    )

    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"{PUBLIC_SCHEMA_BASE}query_mcp.v1.json",
        "manifest_version": 1,
        "interface_version": MCP_INTERFACE_VERSION,
        "producer": {"name": "semantic-rails", "version": __version__},
        "mcp_protocol": {
            "default": MCP_PROTOCOL_VERSION,
            "supported": list(MCP_SUPPORTED_PROTOCOL_VERSIONS),
        },
        "resultSchema": MCP_RESULT_SCHEMA,
        "tools": list_tool_definitions(),
        "resources": list_resource_definitions(),
        "prompts": list_prompt_definitions(),
    }


def architect_mcp_manifest_document() -> dict[str, Any]:
    """Build the complete Architect MCP v1 manifest from FastMCP definitions."""

    from semantic_rails import __version__
    from semantic_rails.architect_mcp import (
        ARCHITECT_INTERFACE_VERSION,
        create_architect_mcp_server,
    )
    from semantic_rails.mcp_server import (
        MCP_PROTOCOL_VERSION,
        MCP_SUPPORTED_PROTOCOL_VERSIONS,
    )

    server = create_architect_mcp_server(workspace_root="/semantic-rails-architect-contract")

    async def definitions() -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
        tools = [
            row.model_dump(by_alias=True, exclude_none=True) for row in await server.list_tools()
        ]
        prompts = [
            row.model_dump(by_alias=True, exclude_none=True) for row in await server.list_prompts()
        ]
        return tools, prompts

    tools, prompts = asyncio.run(definitions())
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"{PUBLIC_SCHEMA_BASE}architect_mcp.v1.json",
        "manifest_version": 1,
        "interface_version": ARCHITECT_INTERFACE_VERSION,
        "producer": {"name": "semantic-rails", "version": __version__},
        "mcp_protocol": {
            "default": MCP_PROTOCOL_VERSION,
            "supported": list(MCP_SUPPORTED_PROTOCOL_VERSIONS),
        },
        "transaction": {
            "revision_format": 1,
            "absent_revision": "absent",
            "optimistic_concurrency": True,
            "caller_idempotency_key": True,
            "cross_process_lock": True,
            "parse_gated_rollback": True,
            "write_free_preview": True,
        },
        "tools": tools,
        "prompts": prompts,
    }


def generated_artifacts() -> dict[str, dict[str, Any]]:
    """Return every code-derived contract keyed by packaged filename."""

    return {
        "architect_mcp.v1.json": architect_mcp_manifest_document(),
        "http_api.v1.openapi.json": http_openapi_document(),
        "query_mcp.v1.json": query_mcp_manifest_document(),
    }


def render_artifact(payload: dict[str, Any]) -> str:
    """Render a deterministic JSON artifact."""

    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
