USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SEMANTIC_WH;
USE DATABASE ANALYTICS;
USE SCHEMA SEMANTIC_COMPARISON;

CREATE STAGE IF NOT EXISTS SEMANTIC_LOAD_STAGE;

COPY INTO COMPARISON_ORDERS
FROM @SEMANTIC_LOAD_STAGE/comparison_orders.csv
FILE_FORMAT = (TYPE = CSV PARSE_HEADER = TRUE FIELD_OPTIONALLY_ENCLOSED_BY = '"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO COMPARISON_ORDER_ITEMS
FROM @SEMANTIC_LOAD_STAGE/comparison_order_items.csv
FILE_FORMAT = (TYPE = CSV PARSE_HEADER = TRUE FIELD_OPTIONALLY_ENCLOSED_BY = '"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO COMPARISON_CUSTOMERS
FROM @SEMANTIC_LOAD_STAGE/comparison_customers.csv
FILE_FORMAT = (TYPE = CSV PARSE_HEADER = TRUE FIELD_OPTIONALLY_ENCLOSED_BY = '"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO COMPARISON_STORES
FROM @SEMANTIC_LOAD_STAGE/comparison_stores.csv
FILE_FORMAT = (TYPE = CSV PARSE_HEADER = TRUE FIELD_OPTIONALLY_ENCLOSED_BY = '"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO COMPARISON_CUSTOMER_HISTORY
FROM @SEMANTIC_LOAD_STAGE/comparison_customer_history.csv
FILE_FORMAT = (TYPE = CSV PARSE_HEADER = TRUE FIELD_OPTIONALLY_ENCLOSED_BY = '"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO COMPARISON_ORDER_LIFECYCLE
FROM @SEMANTIC_LOAD_STAGE/comparison_order_lifecycle.csv
FILE_FORMAT = (TYPE = CSV PARSE_HEADER = TRUE FIELD_OPTIONALLY_ENCLOSED_BY = '"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO COMPARISON_STOREFRONT_SESSIONS
FROM @SEMANTIC_LOAD_STAGE/comparison_storefront_sessions.csv
FILE_FORMAT = (TYPE = CSV PARSE_HEADER = TRUE FIELD_OPTIONALLY_ENCLOSED_BY = '"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
