USE ROLE ACCOUNTADMIN;

-- Semantic Views are currently an open preview feature.
SELECT SYSTEM$ENABLE_PREVIEW_ACCESS();

CREATE WAREHOUSE IF NOT EXISTS SEMANTIC_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE WAREHOUSE SEMANTIC_WH;

CREATE DATABASE IF NOT EXISTS ANALYTICS;
USE DATABASE ANALYTICS;

CREATE SCHEMA IF NOT EXISTS SEMANTIC_COMPARISON;
USE SCHEMA SEMANTIC_COMPARISON;

CREATE OR REPLACE TABLE COMPARISON_ORDERS (
  ORDER_ID VARCHAR,
  CUSTOMER_ID VARCHAR,
  ORDERED_AT TIMESTAMP_NTZ,
  ORDERED_DATE DATE,
  STORE_ID VARCHAR,
  SUBTOTAL_CENTS NUMBER(38, 0),
  TAX_PAID_CENTS NUMBER(38, 0),
  ORDER_TOTAL_CENTS NUMBER(38, 0),
  CUSTOMER_ORDER_NUMBER NUMBER(38, 0),
  IS_NEW_CUSTOMER_ORDER BOOLEAN,
  IS_LARGE_ORDER BOOLEAN,
  ITEM_COUNT NUMBER(38, 0),
  FOOD_ITEM_COUNT NUMBER(38, 0),
  DRINK_ITEM_COUNT NUMBER(38, 0),
  HAS_FOOD_ITEM BOOLEAN,
  HAS_DRINK_ITEM BOOLEAN,
  ITEM_REVENUE_CENTS NUMBER(38, 0),
  ORDER_COST_CENTS NUMBER(38, 0),
  FOOD_REVENUE_CENTS NUMBER(38, 0),
  DRINK_REVENUE_CENTS NUMBER(38, 0),
  GROSS_PROFIT_CENTS NUMBER(38, 0)
);

CREATE OR REPLACE TABLE COMPARISON_ORDER_ITEMS (
  ITEM_ID VARCHAR,
  ORDER_ID VARCHAR,
  SKU VARCHAR,
  PRODUCT_NAME VARCHAR,
  PRODUCT_TYPE VARCHAR,
  ITEM_REVENUE_CENTS NUMBER(38, 0),
  ITEM_COST_CENTS NUMBER(38, 0),
  ITEM_MARGIN_CENTS NUMBER(38, 0),
  ORDERED_AT TIMESTAMP_NTZ,
  STORE_ID VARCHAR,
  CUSTOMER_ID VARCHAR
);

CREATE OR REPLACE TABLE COMPARISON_CUSTOMERS (
  CUSTOMER_ID VARCHAR,
  CUSTOMER_NAME VARCHAR,
  FIRST_ORDER_AT TIMESTAMP_NTZ,
  LATEST_ORDERED_AT TIMESTAMP_NTZ,
  LIFETIME_ORDER_COUNT NUMBER(38, 0),
  LIFETIME_SPEND_BEFORE_TAX_CENTS NUMBER(38, 0),
  LIFETIME_SPEND_CENTS NUMBER(38, 0),
  LIFETIME_TAX_PAID_CENTS NUMBER(38, 0),
  CUSTOMER_TYPE VARCHAR
);

CREATE OR REPLACE TABLE COMPARISON_STORES (
  STORE_ID VARCHAR,
  STORE_NAME VARCHAR,
  OPENED_AT TIMESTAMP_NTZ,
  TAX_RATE FLOAT
);

CREATE OR REPLACE TABLE COMPARISON_CUSTOMER_HISTORY (
  CUSTOMER_ID VARCHAR,
  CUSTOMER_SEGMENT VARCHAR,
  PREFERRED_STORE_ID VARCHAR,
  VALID_FROM TIMESTAMP_NTZ,
  VALID_TO TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE COMPARISON_ORDER_LIFECYCLE (
  ORDER_ID VARCHAR,
  CUSTOMER_ID VARCHAR,
  STORE_ID VARCHAR,
  SUBTOTAL_CENTS NUMBER(38, 0),
  ORDER_TOTAL_CENTS NUMBER(38, 0),
  ORDERED_AT TIMESTAMP_NTZ,
  PREPARED_AT TIMESTAMP_NTZ,
  DELIVERED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE COMPARISON_STOREFRONT_SESSIONS (
  SESSION_ID VARCHAR,
  CUSTOMER_ID VARCHAR,
  STORE_ID VARCHAR,
  STARTED_AT TIMESTAMP_NTZ,
  CONVERTED_ORDER_ID VARCHAR,
  CONVERTED_AT TIMESTAMP_NTZ
);
