USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SEMANTIC_WH;
USE DATABASE ANALYTICS;
USE SCHEMA SEMANTIC_COMPARISON;

SELECT 'COMPARISON_ORDERS' AS table_name, COUNT(*) AS row_count FROM COMPARISON_ORDERS
UNION ALL
SELECT 'COMPARISON_ORDER_ITEMS', COUNT(*) FROM COMPARISON_ORDER_ITEMS
UNION ALL
SELECT 'COMPARISON_CUSTOMERS', COUNT(*) FROM COMPARISON_CUSTOMERS
UNION ALL
SELECT 'COMPARISON_STORES', COUNT(*) FROM COMPARISON_STORES
UNION ALL
SELECT 'COMPARISON_CUSTOMER_HISTORY', COUNT(*) FROM COMPARISON_CUSTOMER_HISTORY
UNION ALL
SELECT 'COMPARISON_ORDER_LIFECYCLE', COUNT(*) FROM COMPARISON_ORDER_LIFECYCLE
UNION ALL
SELECT 'COMPARISON_STOREFRONT_SESSIONS', COUNT(*) FROM COMPARISON_STOREFRONT_SESSIONS
ORDER BY 1;

-- Expected row counts:
-- COMPARISON_ORDERS: 59652
-- COMPARISON_ORDER_ITEMS: 95368
-- COMPARISON_CUSTOMERS: 939
-- COMPARISON_STORES: 5
-- COMPARISON_CUSTOMER_HISTORY: 7
-- COMPARISON_ORDER_LIFECYCLE: 11
-- COMPARISON_STOREFRONT_SESSIONS: 10

SELECT MIN(ORDERED_AT) AS min_ordered_at, MAX(ORDERED_AT) AS max_ordered_at
FROM COMPARISON_ORDERS;
