"""Record how a downstream embedder uses ``semantic_rails.embedding``.

    uv run python scripts/embedding_consumer_contract.py --consumer PATH [--check]

Scans every Python file tracked in the embedder's git checkout for the facade
names it uses and how: the attributes it reads, the argument shapes it calls
with, and the protocols it implements. Each use that works against this engine
is written, one per line, to ``USES_FILE``;
``tests/semantic_rails/test_embedding_consumer_contract.py`` checks them on every
pull request. ``--check`` compares instead of writing and exits 1 when the
embedder's use has drifted from the recorded list.

A use reads like the code it came from:

    Runtime.from_path(_)                 class attribute called with one positional argument
    Runtime().set_adapter(_)             method called on an instance
    Runtime().package_id                 attribute read on an instance
    SemanticHTTPService(_, package_id=)  positional and keyword arguments
    emit_audit_event(**)                 a call that unpacks arguments (``*`` or ``**``)
    AuditSink{emit(self, payload)}       a protocol's members and exact parameters

The engine calls the embedder's implementation of a protocol, so a protocol the
embedder names, or that appears in the annotations of a facade callable it
calls, is recorded whole, and any change to it fails. A method reached through
an object the scan can't place is recorded as an attribute read, so only its
existence is checked.

Instances are found by name: within a file, a name or attribute assigned from a
facade class or from a facade callable annotated to return one; across files,
an attribute that such an instance was stored on (``Entry(service=service)``
makes ``entry.service`` one). That guess also matches test doubles and unrelated
objects of the same name, so uses the engine doesn't have are reported and left
out. Objects passed around any other way are invisible here; the embedder's own
tests against engine ``main`` cover them.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import inspect
import re
import subprocess
import sys
import textwrap
from pathlib import Path
from typing import Any

import semantic_rails.embedding as embedding

FACADE = "semantic_rails.embedding"
REPO_ROOT = Path(__file__).resolve().parents[1]
USES_FILE = REPO_ROOT / "tests" / "semantic_rails" / "fixtures" / "embedding_consumer_uses.txt"
HEADER = (
    "# Generated by scripts/embedding_consumer_contract.py from a downstream embedder's code;\n"
    "# don't edit by hand. One semantic_rails.embedding use per line.\n"
)
# Calls whose arguments name an attribute they replace, e.g. ``monkeypatch.setattr(mod, "X", …)``.
_PATCHING_CALLS = frozenset({"setattr", "delattr", "patch", "object"})
_USE = re.compile(
    r"(?P<name>\w+)(?:(?P<instance>\(\))?\.(?P<attr>\w+))?(?P<args>\([^()]*\))?(?P<protocol>\{[^{}]*\})?"
)


def problem(use: str) -> str | None:
    """Why ``use`` fails against this engine, or None when it works."""
    match = _USE.fullmatch(use)
    if not match:
        return "unrecognised use"
    name, instance, attr, args, protocol = match.group(
        "name", "instance", "attr", "args", "protocol"
    )
    if name not in embedding.__all__:
        return f"{FACADE} no longer exports {name}"
    owner = target = getattr(embedding, name)
    if protocol is not None:
        current = f"{{{_protocol_shape(owner)}}}"
        if current == protocol:
            return None
        return f"{name} is now {current}; the embedder implements it, so update that first"
    if attr and instance and not inspect.isclass(owner):
        return f"{name} is no longer a class"
    if attr and instance and attr not in _instance_attributes(owner):
        return f"{name} instances have no attribute {attr!r}"
    if attr and not instance and not hasattr(owner, attr):
        return f"{name} has no attribute {attr!r}"
    if attr:
        target = getattr(owner, attr, None)
    try:
        signature = inspect.signature(target)
    except (TypeError, ValueError):
        return None  # not called, or no introspectable signature
    if args is None:
        return None
    parts = [part for part in args[1:-1].split(", ") if part]
    positional = [None] * parts.count("_")
    if instance and inspect.isfunction(inspect.getattr_static(owner, attr, None)):
        positional.append(None)  # self
    keywords = {part[:-1]: None for part in parts if part.endswith("=")}
    bind = signature.bind_partial if {"*", "**"} & set(parts) else signature.bind
    try:
        bind(*positional, **keywords)
    except TypeError as exc:
        return f"{signature} no longer accepts this call: {exc}"
    return None


def _instance_attributes(cls: type) -> set[str]:
    """Class attributes, annotations, and attributes the engine's methods assign on ``self``."""
    names = set(dir(cls))
    for klass in cls.__mro__:
        if not klass.__module__.startswith("semantic_rails"):
            continue
        names.update(inspect.get_annotations(klass))
        try:
            tree = ast.parse(textwrap.dedent(inspect.getsource(klass)))
        except (OSError, TypeError):
            continue
        names.update(
            node.attr
            for node in ast.walk(tree)
            if isinstance(node, ast.Attribute)
            and isinstance(node.ctx, ast.Store)
            and isinstance(node.value, ast.Name)
            and node.value.id == "self"
        )
    return names


def _parameters(function: Any) -> str:
    parts: list[str] = []
    keyword_only = False
    for parameter in inspect.signature(function).parameters.values():
        if parameter.kind is parameter.KEYWORD_ONLY and not keyword_only:
            parts.append("*")
        keyword_only |= parameter.kind in (parameter.KEYWORD_ONLY, parameter.VAR_POSITIONAL)
        stars = "**" if parameter.kind is parameter.VAR_KEYWORD else ""
        stars = "*" if parameter.kind is parameter.VAR_POSITIONAL else stars
        default = "" if parameter.default is parameter.empty else "="
        parts.append(f"{stars}{parameter.name}{default}")
    return ", ".join(parts)


def _protocol_shape(cls: Any) -> str | None:
    """A protocol's members, with each method's parameters; None for anything else."""
    if not (inspect.isclass(cls) and getattr(cls, "_is_protocol", False)):
        return None
    members = sorted(
        n for n in {*vars(cls), *inspect.get_annotations(cls)} if not n.startswith("_")
    )
    shapes = [
        f"{member}({_parameters(value)})"
        if callable(value := getattr(cls, member, None))
        else member
        for member in members
    ]
    return "; ".join(shapes)


def _mentions(use: str) -> set[str]:
    """The facade name a use starts with, and the names in the annotations of what it calls."""
    match = _USE.fullmatch(use)
    if not match:
        return set()
    target: Any = getattr(embedding, match["name"], None)
    target = getattr(target, match["attr"], None) if match["attr"] else target
    try:
        annotations = " ".join(
            str(p.annotation) for p in inspect.signature(target).parameters.values()
        )
    except (TypeError, ValueError):
        annotations = ""
    return {match["name"], *re.findall(r"\w+", annotations)}


def _produces(name: str, attr: str | None) -> str | None:
    """The facade class that calling ``name`` (or ``name.attr``) returns, if the engine says so."""
    target: Any = getattr(embedding, name, None)
    if attr is None and inspect.isclass(target):
        return name
    try:
        returned = inspect.signature(getattr(target, attr) if attr else target).return_annotation
    except (AttributeError, TypeError, ValueError):
        return None
    returned = getattr(returned, "__name__", returned)
    exported = isinstance(returned, str) and inspect.isclass(getattr(embedding, returned, None))
    return returned if exported else None


def _shape(call: ast.Call) -> str:
    parts = ["*" if isinstance(arg, ast.Starred) else "_" for arg in call.args]
    parts += sorted(f"{kw.arg}=" for kw in call.keywords if kw.arg)
    parts += ["**"] * any(kw.arg is None for kw in call.keywords)
    return f"({', '.join(parts)})"


def _key(node: ast.expr) -> str | None:
    if isinstance(node, ast.Name):
        return node.id
    return node.attr if isinstance(node, ast.Attribute) else None


def _root(node: ast.expr) -> str | None:
    while isinstance(node, ast.Attribute):
        node = node.value
    return _key(node)


def _string(node: ast.expr) -> str | None:
    return node.value if isinstance(node, ast.Constant) and isinstance(node.value, str) else None


class _FileScan:
    def __init__(self, tree: ast.Module) -> None:
        self.nodes = list(ast.walk(tree))
        self.names: dict[str, str] = {}  # local alias -> facade name
        self.modules: set[str] = set()  # expressions that denote the facade module
        self.imported: set[str] = set()  # names bound by ``import``, which are never instances
        for node in self.nodes:
            self._record_import(node)
        self.instances: dict[str, str] = {}  # name or attribute -> facade class
        for node in self.nodes:
            if isinstance(node, (ast.Assign, ast.AnnAssign)) and isinstance(node.value, ast.Call):
                ref = self._facade_ref(node.value.func)
                produced = _produces(*ref) if ref else None
                targets = node.targets if isinstance(node, ast.Assign) else [node.target]
                keys = filter(None, map(_key, targets))
                self.instances.update(dict.fromkeys(keys, produced) if produced else {})
        handoffs = [
            (kw.arg, kw.value) for n in self.nodes if isinstance(n, ast.Call) for kw in n.keywords
        ]
        handoffs += [
            (target.attr, n.value)
            for n in self.nodes
            if isinstance(n, ast.Assign)
            for target in n.targets
            if isinstance(target, ast.Attribute)
        ]
        self.members = {  # attribute -> facade class, shared with every file
            key: self.instances[value.id]
            for key, value in handoffs
            if key and isinstance(value, ast.Name) and value.id in self.instances
        }

    def _record_import(self, node: ast.AST) -> None:
        if isinstance(node, ast.ImportFrom) and node.level == 0:
            for alias in node.names:
                if node.module == FACADE:
                    self.names[alias.asname or alias.name] = alias.name
                elif f"{node.module}.{alias.name}" == FACADE:
                    self.modules.add(alias.asname or alias.name)
        elif isinstance(node, ast.Import):
            self.modules.update(
                alias.asname or FACADE for alias in node.names if alias.name == FACADE
            )
            self.imported.update(alias.asname or alias.name.split(".")[0] for alias in node.names)

    def _facade_ref(self, node: ast.expr) -> tuple[str, str | None] | None:
        """The facade name, and attribute of it, that ``node`` denotes: ``Runtime.from_path``."""
        if isinstance(node, ast.Name) and node.id in self.names:
            return self.names[node.id], None
        if not isinstance(node, ast.Attribute) or node.attr.startswith("__"):
            return None
        if ast.unparse(node.value) in self.modules:
            return node.attr, None
        base = self._facade_ref(node.value)
        return (base[0], node.attr) if base and base[1] is None else None

    def uses(self, members: dict[str, str]) -> set[str]:
        found: set[str] = set()
        for node in self.nodes:
            if isinstance(node, ast.Call):
                target = self._use(node.func, members)
                found.update([target + _shape(node)] if target else [])
                found.update(filter(None, [self._patched(node)]))
            elif isinstance(node, (ast.Name, ast.Attribute)):
                found.update(filter(None, [self._use(node, members)]))
        return found

    def _use(self, node: ast.expr, members: dict[str, str]) -> str | None:
        ref = self._facade_ref(node)
        if ref:
            return ".".join(filter(None, ref))
        if not isinstance(node, ast.Attribute) or node.attr.startswith("__"):
            return None
        owner = self.instances.get(_key(node.value) or "")
        if owner is None and isinstance(node.value, ast.Attribute):
            owner = None if _root(node.value) in self.imported else members.get(node.value.attr)
        return f"{owner}().{node.attr}" if owner else None

    def _patched(self, call: ast.Call) -> str | None:
        if _key(call.func) not in _PATCHING_CALLS or not call.args:
            return None
        dotted = _string(call.args[0]) or ""
        if dotted.startswith(f"{FACADE}."):
            return dotted.removeprefix(f"{FACADE}.")
        attr = _string(call.args[1]) if len(call.args) > 1 else None
        if attr is None:
            return None
        if ast.unparse(call.args[0]) in self.modules:
            return attr
        ref = self._facade_ref(call.args[0])
        return f"{ref[0]}.{attr}" if ref and ref[1] is None else None


def scan(consumer: Path) -> tuple[list[str], dict[str, str]]:
    """The consumer's uses that work against this engine, and why the others don't."""
    listed = subprocess.run(
        ["git", "-C", str(consumer), "ls-files", "-z", "--", "*.py"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.split("\0")
    files = [
        _FileScan(ast.parse((consumer / name).read_text(encoding="utf-8"), filename=name))
        for name in filter(None, listed)
    ]
    members = {key: owner for scanned in files for key, owner in scanned.members.items()}
    found = set().union(*(scanned.uses(members) for scanned in files))
    named = set().union(*map(_mentions, found)) & set(embedding.__all__)
    shapes = {name: _protocol_shape(getattr(embedding, name)) for name in named}
    found |= {f"{name}{{{shape}}}" for name, shape in shapes.items() if shape is not None}
    failing = {use: reason for use in sorted(found) if (reason := problem(use))}
    working = found - set(failing)
    # ``Runtime`` is implied by ``Runtime.from_path(_)``; keep only the most specific uses.
    prefixes = {use: (f"{use}(", f"{use}.", f"{use}{{") for use in working}
    kept = sorted(u for u in working if not any(o.startswith(prefixes[u]) for o in working))
    return kept, failing


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--consumer", type=Path, required=True, help="the embedder's git checkout")
    parser.add_argument("--check", action="store_true", help="exit 1 if the recorded uses differ")
    args = parser.parse_args(argv)
    kept, failing = scan(args.consumer.resolve())
    for use, reason in failing.items():
        print(f"not recorded: {use}: {reason}", file=sys.stderr)
    text = HEADER + "".join(f"{use}\n" for use in kept)
    if not args.check:
        USES_FILE.write_text(text, encoding="utf-8")
        return 0
    recorded = USES_FILE.read_text(encoding="utf-8")
    sys.stdout.writelines(
        difflib.unified_diff(
            recorded.splitlines(keepends=True),
            text.splitlines(keepends=True),
            fromfile="recorded",
            tofile="consumer",
        )
    )
    return int(text != recorded)


if __name__ == "__main__":
    raise SystemExit(main())
