"""Record how a downstream embedder uses ``semantic_rails.embedding``.

    uv run python scripts/embedding_consumer_contract.py --consumer PATH [--check]

Scans every Python file tracked in the embedder's git checkout for the facade
names it uses and how: the attributes it reads, the argument shapes it calls
with, and the protocols it implements. Each use that works against this engine
is written, one per line, to ``USES_FILE``;
``tests/semantic_rails/test_embedding_consumer_contract.py`` checks them on every
pull request. ``--check`` compares instead of writing and exits 1 when the
embedder's use has drifted from the recorded list.

A use reads like the code it came from:

    Runtime.from_path(_)                 class attribute called with one positional argument
    Runtime().set_adapter(_)             method called on an instance
    Runtime().package_id                 attribute read on an instance
    SemanticHTTPService(_, package_id=)  positional and keyword arguments
    emit_audit_event(**)                 a call that unpacks arguments (``*`` or ``**``)
    AuditSink{emit(self, payload)}       a protocol's members and exact parameters

The engine calls the embedder's implementation of a protocol, so a protocol the
embedder names, or that appears in the annotations of a facade callable it
calls, is recorded whole, and any change to it fails.

Receivers are tracked within lexical scopes, using facade constructors,
annotated return types, explicit instance annotations, and assignments from
known instances. Attribute bindings belong to the exact receiver expression;
member names are never shared between unrelated objects or files. Adding a use
requires a resolved receiver. A recorded instance-member use is retained while
any unresolved receiver still loads or stores that member; removal requires
its absence. Local definitions and reassignments
replace imported bindings, including test doubles that reuse a facade name.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import inspect
import re
import subprocess
import sys
import textwrap
from pathlib import Path
from typing import Any

import semantic_rails.embedding as embedding

FACADE = "semantic_rails.embedding"
REPO_ROOT = Path(__file__).resolve().parents[1]
USES_FILE = REPO_ROOT / "tests" / "semantic_rails" / "fixtures" / "embedding_consumer_uses.txt"
HEADER = (
    "# Generated by scripts/embedding_consumer_contract.py from a downstream embedder's code;\n"
    "# don't edit by hand. One semantic_rails.embedding use per line.\n"
)
# Calls whose arguments name an attribute they replace, e.g. ``monkeypatch.setattr(mod, "X", …)``.
_PATCHING_CALLS = frozenset({"setattr", "delattr", "patch", "object"})
_USE = re.compile(
    r"(?P<name>\w+)(?:(?P<instance>\(\))?\.(?P<attr>\w+))?(?P<args>\([^()]*\))?(?P<protocol>\{[^{}]*\})?"
)


def problem(use: str) -> str | None:
    """Why ``use`` fails against this engine, or None when it works."""
    match = _USE.fullmatch(use)
    if not match:
        return "unrecognised use"
    name, instance, attr, args, protocol = match.group(
        "name", "instance", "attr", "args", "protocol"
    )
    if name not in embedding.__all__:
        return f"{FACADE} no longer exports {name}"
    owner = target = getattr(embedding, name)
    if protocol is not None:
        current = f"{{{_protocol_shape(owner)}}}"
        if current == protocol:
            return None
        return f"{name} is now {current}; the embedder implements it, so update that first"
    if attr and instance and not inspect.isclass(owner):
        return f"{name} is no longer a class"
    if attr and instance and attr not in _instance_attributes(owner):
        return f"{name} instances have no attribute {attr!r}"
    if attr and not instance and not hasattr(owner, attr):
        return f"{name} has no attribute {attr!r}"
    if attr:
        target = getattr(owner, attr, None)
    try:
        signature = inspect.signature(target)
    except (TypeError, ValueError):
        return None  # not called, or no introspectable signature
    if args is None:
        return None
    parts = [part for part in args[1:-1].split(", ") if part]
    positional = [None] * parts.count("_")
    if instance and inspect.isfunction(inspect.getattr_static(owner, attr, None)):
        positional.append(None)  # self
    keywords = {part[:-1]: None for part in parts if part.endswith("=")}
    bind = signature.bind_partial if {"*", "**"} & set(parts) else signature.bind
    try:
        bind(*positional, **keywords)
    except TypeError as exc:
        return f"{signature} no longer accepts this call: {exc}"
    return None


def _instance_attributes(cls: type) -> set[str]:
    """Class attributes, annotations, and attributes the engine's methods assign on ``self``."""
    names = set(dir(cls))
    for klass in cls.__mro__:
        if not klass.__module__.startswith("semantic_rails"):
            continue
        names.update(inspect.get_annotations(klass))
        try:
            tree = ast.parse(textwrap.dedent(inspect.getsource(klass)))
        except (OSError, TypeError):
            continue
        names.update(
            node.attr
            for node in ast.walk(tree)
            if isinstance(node, ast.Attribute)
            and isinstance(node.ctx, ast.Store)
            and isinstance(node.value, ast.Name)
            and node.value.id == "self"
        )
    return names


def _parameters(function: Any) -> str:
    parts: list[str] = []
    keyword_only = False
    parameters = list(inspect.signature(function).parameters.values())
    positional_only = sum(parameter.kind is parameter.POSITIONAL_ONLY for parameter in parameters)
    for index, parameter in enumerate(parameters, start=1):
        if parameter.kind is parameter.KEYWORD_ONLY and not keyword_only:
            parts.append("*")
        keyword_only |= parameter.kind in (parameter.KEYWORD_ONLY, parameter.VAR_POSITIONAL)
        stars = "**" if parameter.kind is parameter.VAR_KEYWORD else ""
        stars = "*" if parameter.kind is parameter.VAR_POSITIONAL else stars
        default = "" if parameter.default is parameter.empty else "="
        parts.append(f"{stars}{parameter.name}{default}")
        parts += ["/"] * (index == positional_only)
    return ", ".join(parts)


def _protocol_shape(cls: Any) -> str | None:
    """A protocol's members, with each method's parameters; None for anything else."""
    if not (inspect.isclass(cls) and getattr(cls, "_is_protocol", False)):
        return None
    members = sorted(
        n for n in {*vars(cls), *inspect.get_annotations(cls)} if not n.startswith("_")
    )
    shapes = [
        f"{member}({_parameters(value)})"
        if callable(value := getattr(cls, member, None))
        else member
        for member in members
    ]
    return "; ".join(shapes)


def _mentions(use: str) -> set[str]:
    """The facade name a use starts with, and the names in the annotations of what it calls."""
    match = _USE.fullmatch(use)
    if not match:
        return set()
    target: Any = getattr(embedding, match["name"], None)
    target = getattr(target, match["attr"], None) if match["attr"] else target
    try:
        annotations = " ".join(
            str(p.annotation) for p in inspect.signature(target).parameters.values()
        )
    except (TypeError, ValueError):
        annotations = ""
    return {match["name"], *re.findall(r"\w+", annotations)}


def _produces(name: str, attr: str | None) -> str | None:
    """The facade class that calling ``name`` (or ``name.attr``) returns, if the engine says so."""
    target: Any = getattr(embedding, name, None)
    if attr is None and inspect.isclass(target):
        return name
    try:
        returned = inspect.signature(getattr(target, attr) if attr else target).return_annotation
    except (AttributeError, TypeError, ValueError):
        return None
    returned = getattr(returned, "__name__", returned)
    exported = isinstance(returned, str) and inspect.isclass(getattr(embedding, returned, None))
    return returned if exported else None


def _shape(call: ast.Call) -> str:
    parts = ["*" if isinstance(arg, ast.Starred) else "_" for arg in call.args]
    parts += sorted(f"{kw.arg}=" for kw in call.keywords if kw.arg)
    parts += ["**"] * any(kw.arg is None for kw in call.keywords)
    return f"({', '.join(parts)})"


def _key(node: ast.expr) -> str | None:
    if isinstance(node, ast.Name):
        return node.id
    return node.attr if isinstance(node, ast.Attribute) else None


def _string(node: ast.expr) -> str | None:
    return node.value if isinstance(node, ast.Constant) and isinstance(node.value, str) else None


class _FileScan(ast.NodeVisitor):
    def __init__(self, tree: ast.Module) -> None:
        # Bindings are facade names, module aliases, or instance owners. None
        # explicitly shadows an outer binding without claiming an engine type.
        self.scopes: list[dict[str, tuple[str, str] | None]] = [{}]
        self.found: set[str] = set()
        self.opaque_members: set[str] = set()
        self.visit(tree)

    def _lookup(self, key: str) -> tuple[str, str] | None:
        for scope in reversed(self.scopes):
            if key in scope:
                return scope[key]
        return None

    def _binding(self, node: ast.expr) -> tuple[str, str] | None:
        if isinstance(node, ast.Name):
            return self._lookup(node.id)
        if not isinstance(node, ast.Attribute) or node.attr.startswith("__"):
            return None
        exact = ast.unparse(node)
        root: ast.expr = node
        while isinstance(root, ast.Attribute):
            root = root.value
        for scope in reversed(self.scopes):
            if exact in scope:
                return scope[exact]
            if isinstance(root, ast.Name) and root.id in scope:
                break
        base = self._binding(node.value)
        if base and base[0] == "module":
            return "symbol", node.attr
        return None

    def _facade_ref(self, node: ast.expr) -> tuple[str, str | None] | None:
        binding = self._binding(node)
        if binding and binding[0] == "symbol":
            return binding[1], None
        if isinstance(node, ast.Attribute) and not node.attr.startswith("__"):
            base = self._binding(node.value)
            if base and base[0] == "symbol":
                return base[1], node.attr
        return None

    def _instance(self, node: ast.expr) -> str | None:
        if isinstance(node, ast.Call):
            binding = self._binding(node.func)
            if binding and binding[0] == "factory":
                return binding[1]
            ref = self._facade_ref(node.func)
            return _produces(*ref) if ref else None
        binding = self._binding(node)
        return binding[1] if binding and binding[0] == "instance" else None

    def _annotation(self, node: ast.expr | None) -> str | None:
        if node is None:
            return None
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            try:
                node = ast.parse(node.value, mode="eval").body
            except SyntaxError:
                return None
        if isinstance(node, ast.BinOp) and isinstance(node.op, ast.BitOr):
            if isinstance(node.right, ast.Constant) and node.right.value is None:
                return self._annotation(node.left)
            if isinstance(node.left, ast.Constant) and node.left.value is None:
                return self._annotation(node.right)
        ref = self._facade_ref(node)
        if ref and ref[1] is None and inspect.isclass(getattr(embedding, ref[0], None)):
            return ref[0]
        return None

    def _bind(self, target: ast.expr, binding: tuple[str, str] | None) -> None:
        if isinstance(target, (ast.Tuple, ast.List)):
            for element in target.elts:
                self._bind(element, None)
        elif isinstance(target, (ast.Name, ast.Attribute)):
            key = ast.unparse(target)
            # Replacing an object invalidates its previously known members.
            for member in list(self.scopes[-1]):
                if member.startswith(key + "."):
                    del self.scopes[-1][member]
            self.scopes[-1][key] = binding

    def visit_ImportFrom(self, node: ast.ImportFrom) -> None:
        for alias in node.names:
            binding = None
            if node.level == 0 and node.module == FACADE:
                binding = ("symbol", alias.name)
            elif node.level == 0 and f"{node.module}.{alias.name}" == FACADE:
                binding = ("module", FACADE)
            self.scopes[-1][alias.asname or alias.name] = binding

    def visit_Import(self, node: ast.Import) -> None:
        for alias in node.names:
            key = alias.asname or alias.name.split(".")[0]
            self.scopes[-1][key] = None
            if alias.name == FACADE:
                self.scopes[-1][alias.asname or FACADE] = ("module", FACADE)

    def visit_Assign(self, node: ast.Assign) -> None:
        self.visit(node.value)
        owner = self._instance(node.value)
        binding = ("instance", owner) if owner else self._binding(node.value)
        for target in node.targets:
            self.visit(target)
            self._bind(target, binding)

    def visit_AnnAssign(self, node: ast.AnnAssign) -> None:
        self.visit(node.annotation)
        if node.value is not None:
            self.visit(node.value)
            owner = self._instance(node.value) or self._annotation(node.annotation)
        else:
            owner = self._annotation(node.annotation)
        self.visit(node.target)
        self._bind(node.target, ("instance", owner) if owner else None)

    def visit_AugAssign(self, node: ast.AugAssign) -> None:
        self.generic_visit(node)
        self._bind(node.target, None)

    def visit_FunctionDef(self, node: ast.FunctionDef | ast.AsyncFunctionDef) -> None:
        for decorator in node.decorator_list:
            self.visit(decorator)
        for default in [*node.args.defaults, *filter(None, node.args.kw_defaults)]:
            self.visit(default)
        arguments = [*node.args.posonlyargs, *node.args.args, *node.args.kwonlyargs]
        arguments += [arg for arg in (node.args.vararg, node.args.kwarg) if arg]
        bindings: dict[str, tuple[str, str] | None] = {}
        for arg in arguments:
            if arg.annotation is not None:
                self.visit(arg.annotation)
            owner = self._annotation(arg.annotation)
            bindings[arg.arg] = ("instance", owner) if owner else None
        if node.returns is not None:
            self.visit(node.returns)
        returned = self._annotation(node.returns)
        self.scopes[-1][node.name] = ("factory", returned) if returned else None

        # All function-local names shadow outer bindings even before assignment.
        class Locals(ast.NodeVisitor):
            def visit_Name(self, name: ast.Name) -> None:
                if isinstance(name.ctx, ast.Store):
                    bindings.setdefault(name.id, None)

            def visit_FunctionDef(self, node: ast.FunctionDef | ast.AsyncFunctionDef) -> None:
                bindings.setdefault(node.name, None)

            visit_AsyncFunctionDef = visit_FunctionDef

            def visit_ClassDef(self, klass: ast.ClassDef) -> None:
                bindings.setdefault(klass.name, None)

            def visit_ImportFrom(self, imported: ast.ImportFrom) -> None:
                for alias in imported.names:
                    bindings.setdefault(alias.asname or alias.name, None)

            def visit_Import(self, imported: ast.Import) -> None:
                for alias in imported.names:
                    bindings.setdefault(alias.asname or alias.name.split(".")[0], None)

        collector = Locals()
        for statement in node.body:
            collector.visit(statement)
        self.scopes.append(bindings)
        for statement in node.body:
            self.visit(statement)
        self.scopes.pop()

    visit_AsyncFunctionDef = visit_FunctionDef

    def visit_ClassDef(self, node: ast.ClassDef) -> None:
        for expression in [*node.decorator_list, *node.bases]:
            self.visit(expression)
        self.scopes[-1][node.name] = None
        self.scopes.append({})
        for statement in node.body:
            self.visit(statement)
        self.scopes.pop()

    def visit_If(self, node: ast.If) -> None:
        self.visit(node.test)
        before = self.scopes[-1].copy()
        branches = []
        for body in (node.body, node.orelse):
            self.scopes[-1] = before.copy()
            for statement in body:
                self.visit(statement)
            branches.append(self.scopes[-1])
        self.scopes[-1] = {
            key: branches[0].get(key) if branches[0].get(key) == branches[1].get(key) else None
            for key in branches[0].keys() | branches[1].keys()
        }

    def visit_For(self, node: ast.For | ast.AsyncFor) -> None:
        self.visit(node.iter)
        self.visit(node.target)
        self._bind(node.target, None)
        self._loop(node.body, node.orelse)

    visit_AsyncFor = visit_For

    def visit_While(self, node: ast.While) -> None:
        self._loop(node.body, node.orelse, node.test)

    def _loop(
        self, body: list[ast.stmt], otherwise: list[ast.stmt], test: ast.expr | None = None
    ) -> None:
        # A later iteration may observe any assignment in the body. Do not
        # assume that the pre-loop value is still the receiver's type.
        targets = [
            child
            for statement in body
            for child in ast.walk(statement)
            if isinstance(child, (ast.Name, ast.Attribute)) and isinstance(child.ctx, ast.Store)
        ]
        for target in targets:
            self._bind(target, None)
        if test is not None:
            self.visit(test)
        for statement in body:
            self.visit(statement)
        for target in targets:
            self._bind(target, None)
        for statement in otherwise:
            self.visit(statement)

    def visit_With(self, node: ast.With | ast.AsyncWith) -> None:
        for item in node.items:
            self.visit(item.context_expr)
            if item.optional_vars is not None:
                self.visit(item.optional_vars)
                self._bind(item.optional_vars, None)
        for statement in node.body:
            self.visit(statement)

    visit_AsyncWith = visit_With

    def visit_Lambda(self, node: ast.Lambda) -> None:
        args = [*node.args.posonlyargs, *node.args.args, *node.args.kwonlyargs]
        args += [arg for arg in (node.args.vararg, node.args.kwarg) if arg]
        self.scopes.append(dict.fromkeys(arg.arg for arg in args))
        self.visit(node.body)
        self.scopes.pop()

    def visit_NamedExpr(self, node: ast.NamedExpr) -> None:
        self.visit(node.value)
        owner = self._instance(node.value)
        self._bind(node.target, ("instance", owner) if owner else self._binding(node.value))

    def visit_Call(self, node: ast.Call) -> None:
        target = self._use(node.func)
        if target:
            self.found.add(target + _shape(node))
        patched = self._patched(node)
        if patched:
            self.found.add(patched)
        self.generic_visit(node)

    def visit_Name(self, node: ast.Name) -> None:
        if isinstance(node.ctx, ast.Load) and (use := self._use(node)):
            self.found.add(use)

    def visit_Attribute(self, node: ast.Attribute) -> None:
        if (
            isinstance(node.ctx, (ast.Load, ast.Store))
            and not node.attr.startswith("__")
            and self._instance(node.value) is None
        ):
            self.opaque_members.add(node.attr)
        if isinstance(node.ctx, ast.Load) and (use := self._use(node)):
            self.found.add(use)
        self.generic_visit(node)

    def _use(self, node: ast.expr) -> str | None:
        ref = self._facade_ref(node)
        if ref:
            return ".".join(filter(None, ref))
        if isinstance(node, ast.Attribute) and not node.attr.startswith("__"):
            owner = self._instance(node.value)
            return f"{owner}().{node.attr}" if owner else None
        return None

    def _patched(self, call: ast.Call) -> str | None:
        if _key(call.func) not in _PATCHING_CALLS or not call.args:
            return None
        dotted = _string(call.args[0]) or ""
        if dotted.startswith(f"{FACADE}."):
            return dotted.removeprefix(f"{FACADE}.")
        attr = _string(call.args[1]) if len(call.args) > 1 else None
        if attr is None:
            return None
        binding = self._binding(call.args[0])
        if binding and binding[0] == "module":
            return attr
        ref = self._facade_ref(call.args[0])
        return f"{ref[0]}.{attr}" if ref and ref[1] is None else None


def scan(consumer: Path) -> tuple[list[str], dict[str, str]]:
    """The consumer's uses that work against this engine, and why the others don't."""
    listed = subprocess.run(
        ["git", "-C", str(consumer), "ls-files", "-z", "--", "*.py"],
        check=True,
        capture_output=True,
        text=True,
        timeout=120,
    ).stdout.split("\0")
    files = [
        _FileScan(ast.parse((consumer / name).read_text(encoding="utf-8"), filename=name))
        for name in filter(None, listed)
    ]
    found = set().union(*(scanned.found for scanned in files))
    named = set().union(*map(_mentions, found)) & set(embedding.__all__)
    shapes = {name: _protocol_shape(getattr(embedding, name)) for name in named}
    found |= {f"{name}{{{shape}}}" for name, shape in shapes.items() if shape is not None}
    opaque_members = set().union(*(scanned.opaque_members for scanned in files))
    for use in USES_FILE.read_text(encoding="utf-8").splitlines():
        match = _USE.fullmatch(use)
        if match and match["instance"] and match["attr"] in opaque_members and use not in found:
            found.add(use)
            print(f"retained (receiver not traced): {use}", file=sys.stderr)
    failing = {use: reason for use in sorted(found) if (reason := problem(use))}
    working = found - set(failing)
    # ``Runtime`` is implied by ``Runtime.from_path(_)``; keep only the most specific uses.
    prefixes = {use: (f"{use}(", f"{use}.", f"{use}{{") for use in working}
    kept = sorted(u for u in working if not any(o.startswith(prefixes[u]) for o in working))
    return kept, failing


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--consumer", type=Path, required=True, help="the embedder's git checkout")
    parser.add_argument("--check", action="store_true", help="exit 1 if the recorded uses differ")
    args = parser.parse_args(argv)
    kept, failing = scan(args.consumer.resolve())
    for use, reason in failing.items():
        print(f"not recorded: {use}: {reason}", file=sys.stderr)
    text = HEADER + "".join(f"{use}\n" for use in kept)
    if not args.check:
        USES_FILE.write_text(text, encoding="utf-8")
        return 0
    recorded = USES_FILE.read_text(encoding="utf-8")
    sys.stdout.writelines(
        difflib.unified_diff(
            recorded.splitlines(keepends=True),
            text.splitlines(keepends=True),
            fromfile="recorded",
            tofile="consumer",
        )
    )
    return int(text != recorded)


if __name__ == "__main__":
    raise SystemExit(main())
